export const FONT_LIST = [
  'Action Man',
  'Autobahn',
  'AvantGarde Bk BT',
  'BabelSans',
  'Benguiat Bk BT',
  'Blue Highway D Type',
  'Blue Highway',
  'Bremen Bd BT',
  'Century Gothic',
  'Corbel',
  'Florencesans',
  'Futura Lt BT',
  'Futura Md BT',
  'Gadugi',
  'GoudyOlSt BT',
  'Humanst521 BT',
  'Junegull',
  'Kabel Bk BT',
  'Leelawadee UI',
  'Lithograph',
  'Medrano',
  'Nirmala UI',
  'Nirmala UI',
  'NotMaryKate',
  'Open Sans',
  'Serifa BT',
  'Serifa BT',
  'Serifa BT',
  'SF Buttacup Lettering',
  'SF Buttacup Lettering',
  'Souvenir Lt BT',
  'Space Frigate',
  'SquareFont',
  'Tapeworm',
  'Ubuntu',
  'Whatafont Expanded',
  'Whatafont',
  'ZapfEllipt BT'
]

export const FONT_STYLES = ['bold', 'italic', 'normal']
